trigger:
  branches:
    include:
      - main  # Change to the branch you're using for production deployment

pool:
  vmImage: 'windows'  # You can change this to use the self-hosted agent

variables:
  buildConfiguration: 'Release'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
      addToPath: true

  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build Next.js app'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/.next'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/nextjs_build'
    displayName: 'Copy build artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/nextjs_build'
      ArtifactName: 'nextjs_build'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'
