trigger:
- main

pool:
  name: 'windows' # Replace with your self-hosted pool name
  demands:
  - npm # Optional: Add capabilities that the agent must support

steps:
# Step 1: Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Use Node.js 16.x'

# Step 2: Install Dependencies
- script: npm install
  displayName: 'Install Dependencies'

# Step 3: Build Application
- script: npm run build
  displayName: 'Build Application'

# Step 4: Publish Artifacts
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/.next'
    artifact: 'drop'
  displayName: 'Publish Build Artifacts'
